Add Angular front-end

diff --git a/install-prereqs b/install-prereqs
--- a/install-prereqs
+++ b/install-prereqs
@@ -11,6 +11,16 @@ else
     exit 1
 fi
 
+if which apt > /dev/null 2>&1; then
+    sudo apt install -y chromium-driver || exit $?
+elif which chromedriver > /dev/null 2>&1; then
+    :
+else
+    echo 'Cannot install chromedriver; please install manually' >&2
+    exit 1
+fi
+
+
 PATH_CMDS=''
 
 add_to_path() {
